function drawMenu(){
 ctx.fillStyle='#83cc6a';ctx.fillRect(0,0,W,H);for(let i=0;i<45;i++){const x=(i*197+Math.sin(menuT*.15+i)*45)%W,y=(i*113+67)%H;ctx.fillStyle=i%3?'#66b957':'#f8e8a2';ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(x,y,3+(i%5),0,TAU);ctx.fill();}ctx.globalAlpha=1;
 const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#173f2a77');grad.addColorStop(1,'#10251bdd');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
 ctx.textAlign='center';ctx.shadowColor='#102418';ctx.shadowBlur=12;ctx.lineWidth=10;ctx.strokeStyle='#fff7dc';ctx.font='900 72px "Microsoft YaHei",sans-serif';ctx.strokeText('萌勇肉鸽大冒险',W/2,160);ctx.fillStyle='#ffb42e';ctx.fillText('萌勇肉鸽大冒险',W/2,160);ctx.shadowBlur=0;
 ctx.font='700 23px sans-serif';ctx.fillStyle='#fff';ctx.fillText('随机技能 × 怪物潮 × 双 Boss × 无限成长',W/2,208);
 const bob=Math.sin(menuT*3)*4;drawImageCentered(A.hero_win,W/2,365+bob,210,null,false,1);
 button(455,545,370,82,'⚔ 开始冒险','#ffb62f','#fff4c9',36);
 ctx.font='600 17px sans-serif';ctx.fillStyle='#f3ffe8';ctx.fillText(`最高分：${fmt(+localStorage.getItem('mengyong_high')||0)}　　WASD/方向键移动 · 手机左侧摇杆`,W/2,670);
}
function drawWorld(){const g=game,p=g.player;ctx.save();if(g.shake){ctx.translate(rand(-g.shake,g.shake),rand(-g.shake,g.shake));}
 drawGround();
 for(const c of g.clouds){const [x,y]=worldToScreen(c.x,c.y);ctx.globalAlpha=.28;ctx.fillStyle='#62d64f';ctx.beginPath();ctx.arc(x,y,c.r,0,TAU);ctx.fill();ctx.globalAlpha=1;for(let i=0;i<5;i++){ctx.fillStyle='#a7ff86';ctx.globalAlpha=.18;ctx.beginPath();ctx.arc(x+Math.sin(game.time*2+i)*c.r*.45,y+Math.cos(game.time*1.8+i)*c.r*.4,14+i*2,0,TAU);ctx.fill();ctx.globalAlpha=1;}}
 for(const m of g.meteors){const [x,y]=worldToScreen(m.x,m.y);if(!m.done){ctx.strokeStyle='#ff6b39';ctx.lineWidth=5;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(x,y,90+m.lv*10,0,TAU);ctx.stroke();ctx.globalAlpha=.25;ctx.fillStyle='#ff944d';ctx.beginPath();ctx.arc(x,y,(1.05-m.t)*(90+m.lv*10),0,TAU);ctx.fill();ctx.globalAlpha=1;}else drawImageCentered(A.fireball_fx,x,y-40,120,null,false,1);}
 for(const o of g.pickups)drawPickup(o);
 for(const e of g.enemies)drawEnemy(e);
 for(const s of g.enemyShots)drawEnemyShot(s);
 for(const q of g.projectiles)drawProjectile(q);
 drawPlayer();
 for(const e of g.effects)drawEffect(e);
 for(const t of g.texts){const [x,y]=worldToScreen(t.x,t.y);ctx.globalAlpha=clamp(t.life/.25,0,1);ctx.font=`800 ${t.size}px sans-serif`;ctx.textAlign='center';ctx.strokeStyle='#172417';ctx.lineWidth=5;ctx.strokeText(t.text,x,y);ctx.fillStyle=t.color;ctx.fillText(t.text,x,y);ctx.globalAlpha=1;}
 ctx.restore();if(g.flash>0){ctx.fillStyle=`rgba(255,255,255,${g.flash})`;ctx.fillRect(0,0,W,H);}}
function drawGround(){const g=game,[ox,oy]=worldToScreen(0,0);ctx.fillStyle='#89d06b';ctx.fillRect(0,0,W,H);const grid=96;const sx=((ox%grid)+grid)%grid,sy=((oy%grid)+grid)%grid;for(let y=sy-grid;y<H+grid;y+=grid)for(let x=sx-grid;x<W+grid;x+=grid){const seed=Math.sin((x-ox)*.013+(y-oy)*.017)*43758.54;const f=seed-Math.floor(seed);if(f>.67){ctx.fillStyle=f>.85?'#fff4b8':'#68b954';ctx.beginPath();ctx.arc(x+22,y+31,3+(f*4|0),0,TAU);ctx.fill();ctx.fillStyle='#5ba549';ctx.fillRect(x+20,y+34,3,9);}if(f<.08){ctx.fillStyle='#68846c';ctx.beginPath();ctx.ellipse(x+42,y+44,18,10,-.3,0,TAU);ctx.fill();ctx.fillStyle='#93a68d';ctx.beginPath();ctx.ellipse(x+38,y+40,12,6,-.3,0,TAU);ctx.fill();}}
 ctx.strokeStyle='#6abd59';ctx.globalAlpha=.25;ctx.lineWidth=2;for(let x=sx;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=sy;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(0?0:W,y);ctx.stroke();}ctx.globalAlpha=1;}
function drawPlayer(){const g=game,p=g.player,[x,y]=worldToScreen(p.x,p.y);const [mx,my]=moveVector();let img=Math.hypot(mx,my)>.1?A.hero_run:A.hero_idle;if(p.invuln>.3)img=A.hero_hurt;drawShadow(x,y+26,28,10);if(p.shield>0){ctx.strokeStyle='#82dcff';ctx.lineWidth=4;ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(x,y,40,0,TAU);ctx.stroke();ctx.fillStyle='#65cfff22';ctx.fill();ctx.globalAlpha=1;}drawImageCentered(img,x,y,78,null,p.face<0,p.invuln>0&&Math.floor(game.time*18)%2?.45:1);
 const lv=p.skills.blades||0;if(lv){const n=1+Math.ceil(lv/2),rad=54+lv*6;for(let i=0;i<n;i++){const a=g.time*(2.4+lv*.18)+i/n*TAU;drawImageCentered(A.blade_fx,x+Math.cos(a)*rad,y+Math.sin(a)*rad,42,null,false,1);}}
 if(p.skills.spirit){drawImageCentered(A.skill_spirit,x+Math.cos(g.time*3)*48,y+Math.sin(g.time*3)*48,36,null,false,.9);}}
function drawEnemy(e){const [x,y]=worldToScreen(e.x,e.y),t=ENEMIES[e.type];if(x<-150||x>W+150||y<-150||y>H+150)return;drawShadow(x,y+e.r*.72,e.r*.85,e.r*.32);drawImageCentered(A[t.img],x,y,e.boss?e.r*2.45:e.r*2.55,null,e.x>game.player.x,e.hit>0?.65:1);if(e.boss){const bw=310,bh=14;ctx.fillStyle='#251817aa';roundRect(x-bw/2,y-e.r-42,bw,bh,7,true,false);ctx.fillStyle=e.type==='boss_tree'?'#8be05b':'#f16d7c';roundRect(x-bw/2+2,y-e.r-40,(bw-4)*clamp(e.hp/e.maxHp,0,1),bh-4,5,true,false);ctx.fillStyle='white';ctx.font='800 17px sans-serif';ctx.textAlign='center';ctx.fillText(e.type==='boss_tree'?'远古树魔':'森林巨菇王',x,y-e.r-51);}}
function drawProjectile(q){const [x,y]=worldToScreen(q.x,q.y);let img=A.fireball_fx,w=42;if(q.type==='ice'){img=A.ice_fx;w=38;}else if(q.type==='leaf'){img=A.leaf_fx;w=48;}else if(q.type==='spirit'){img=A.skill_spirit;w=34;}else if(q.type==='tornado'){img=A.skill_tornado;w=82;}ctx.save();ctx.translate(x,y);ctx.rotate(q.rot||Math.atan2(q.vy,q.vx));drawImageCentered(img,0,0,w,null,false,1);ctx.restore();}
function drawEnemyShot(s){const [x,y]=worldToScreen(s.x,s.y);ctx.fillStyle=s.type==='rock'?'#ff9868':'#a56ddc';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,s.r,0,TAU);ctx.fill();ctx.shadowBlur=0;}
function drawPickup(o){const [x,y]=worldToScreen(o.x,o.y);if(o.type==='coin')drawImageCentered(A.item_coin,x,y,28);else if(o.type==='heal')drawImageCentered(A.item_potion,x,y,30);else{ctx.fillStyle='#64eaff';ctx.shadowColor='#bffaff';ctx.shadowBlur=10;ctx.save();ctx.translate(x,y);ctx.rotate(game.time*2);ctx.fillRect(-6,-6,12,12);ctx.restore();ctx.shadowBlur=0;}}
function drawEffect(e){if(e.type==='line'||e.type==='beam'){const [x1,y1]=worldToScreen(e.x1,e.y1),[x2,y2]=worldToScreen(e.x2,e.y2);ctx.globalAlpha=clamp(e.life/e.max,0,1);ctx.strokeStyle=e.color;ctx.lineWidth=e.type==='beam'?e.width:5;ctx.shadowColor=e.color;ctx.shadowBlur=e.type==='beam'?18:12;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=1;return;}const [x,y]=worldToScreen(e.x,e.y),t=1-e.life/e.max;ctx.globalAlpha=1-t;ctx.strokeStyle=e.color;ctx.fillStyle=e.color;if(e.type==='ring'){ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,e.size*(.5+t*.8),0,TAU);ctx.stroke();}else{for(let i=0;i<9;i++){let a=i/9*TAU;ctx.beginPath();ctx.arc(x+Math.cos(a)*e.size*t*.7,y+Math.sin(a)*e.size*t*.7,5*(1-t)+2,0,TAU);ctx.fill();}}ctx.globalAlpha=1;}
function drawShadow(x,y,rx,ry){ctx.fillStyle='#24402e40';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill();}

